#/*-----------------------------------------------------------------*/
#/*! 
#  \file Makefile.mingw
#  \brief Makefile for mingw (windows)
#  \author  M. Gastineau 
#           Astronomie et Systemes Dynamiques, IMCCE, CNRS, Observatoire de Paris. 
#
#   Copyright, 2016, 2017, CNRS
#   email of the author : Mickael.Gastineau@obspm.fr
#  
#*/
#/*-----------------------------------------------------------------*/
#
#/*-----------------------------------------------------------------*/
#/* License  of this file :
#  This file is "triple-licensed", you have to choose one  of the three licenses 
#  below to apply on this file.
#  
#     CeCILL-C
#     	The CeCILL-C license is close to the GNU LGPL.
#     	( http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html )
#  
#  or CeCILL-B
#        The CeCILL-B license is close to the BSD.
#        (http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt)
#  
#  or CeCILL v2.1
#       The CeCILL license is compatible with the GNU GPL.
#       ( http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html )
#  
# 
# This library is governed by the CeCILL-C, CeCILL-B or the CeCILL license under 
# French law and abiding by the rules of distribution of free software.  
# You can  use, modify and/ or redistribute the software under the terms 
# of the CeCILL-C,CeCILL-B or CeCILL license as circulated by CEA, CNRS and INRIA  
# at the following URL "http://www.cecill.info". 
#
# As a counterpart to the access to the source code and  rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights,  and the successive licensors  have only  limited
# liability. 
#
# In this respect, the user's attention is drawn to the risks associated
# with loading,  using,  modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean  that it is complicated to manipulate,  and  that  also
# therefore means  that it is reserved for developers  and  experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or 
# data to be ensured and,  more generally, to use and operate it in the 
# same conditions as regards security. 
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL-C,CeCILL-B or CeCILL license and that you accept its terms.
# */
# /*-----------------------------------------------------------------*/


ifeq ("$(ENABLEPYTHON)", "1")
PYTHON=$(PPYTHON)
PYTHON_TARGET_ALL=python_all
PYTHON_TARGET_CHECK=python_check
PYTHON_TARGET_CLEAN=python_clean
PYTHON_TARGET_INSTALL=python_install
PYTHON_WITHPATH=PYTHONPATH=../src $(PYTHON)
else
PYTHON_TARGET_ALL=
PYTHON_TARGET_CHECK=
PYTHON_TARGET_CLEAN=
PYTHON_TARGET_INSTALL=
endif

all : $(PYTHON_TARGET_ALL)

check : $(PYTHON_TARGET_CHECK)

clean: $(PYTHON_TARGET_CLEAN)

install : $(PYTHON_TARGET_INSTALL)

 
python_all :

python_check  : checkpy 
	@echo --------------------------------------
	@echo  All tests passed 
	@echo --------------------------------------


reportfailed :
	@echo ------------------------------------------
	@echo Report this bug to inpop.imcce@obspm.fr
	@echo Attach the file calceph.log to your report
	@echo ------------------------------------------
	@exit 1


REPORTFAILED= make -f Makefile.mingw reportfailed

checkpy  : 
	$(PYTHON_WITHPATH) < mopen.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mopenfail.py >calceph.log || $(REPORTFAILED)
	$(PYTHON_WITHPATH) < mgetconstant.py >calceph.log  || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mgetconstantindex.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mcheck.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mcomputeunitfail.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mcomputeunit.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mcomputeunitnaifid.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < morientunitfail.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < getversionstr.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mcomputeorder01.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < mcomputeorder23.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < error.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < timescale.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < timespan.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < getpositionrecordindex.py >calceph.log || $(REPORTFAILED) 
	$(PYTHON_WITHPATH) < getorientrecordindex.py >calceph.log || $(REPORTFAILED) 


#
# Clean target: "make -f Makefile.mingw clean" to remove unwanted 
#               objects and executables.
#
python_clean:

#
# install target: "make -f Makefile.mingw install DESTDIR=xxx" to perform the installation.
#
python_install: 


